#### Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("Resources/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [99]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df2 = application_df.drop(columns=['EIN','NAME'], axis=1)

In [100]:
# Determine the number of unique values in each column.
application_df2.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [101]:
# Look at APPLICATION_TYPE value counts for binning
application_df2['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [102]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = []

for i in range(len(application_df2['APPLICATION_TYPE'].value_counts())):
    if application_df2['APPLICATION_TYPE'].value_counts()[i] < 156:
        application_types_to_replace.append(application_df2['APPLICATION_TYPE'].value_counts().index[i])


# Replace in dataframe
for app in application_types_to_replace:
    application_df2['APPLICATION_TYPE'] = application_df2['APPLICATION_TYPE'].replace(app,"Other")


# Check to make sure binning was successful
application_df2['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: APPLICATION_TYPE, dtype: int64

In [103]:
# Look at CLASSIFICATION value counts for binning
application_df2['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [104]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df2['CLASSIFICATION'].value_counts().loc[lambda x: x>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [105]:
# Choose a cutoff value and create a list of classifications to be replaced

# use the variable name `classifications_to_replace`
classifications_to_replace = []

for i in range(len(application_df2['CLASSIFICATION'].value_counts())):
    if application_df2['CLASSIFICATION'].value_counts()[i] < 30:
        classifications_to_replace.append(application_df2['CLASSIFICATION'].value_counts().index[i])

In [106]:
# Replace in dataframe

for cls in classifications_to_replace:
    application_df2['CLASSIFICATION'] = application_df2['CLASSIFICATION'].replace(cls,"Other")  

    
    # Check to make sure binning was successful
application_df2['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
Other      227
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
Name: CLASSIFICATION, dtype: int64

In [107]:
# Generate our categorical variable lists
charity_cat = application_df2.dtypes[application_df2.dtypes == "object"].index.tolist()

In [108]:
charity_cat

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [109]:
# Convert categorical data to numeric with `pd.get_dummies`
converted_app = pd.get_dummies(application_df2, columns=charity_cat, drop_first=True)

In [110]:
converted_app

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,ORGANIZATION_Trust,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,108590,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,6692,1,0,0,1,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
4,1,142590,1,0,0,1,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34295,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34296,1,5000,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34297,1,5000,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
34298,1,36500179,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [111]:
# Split our preprocessed data into our features and target arrays
y = converted_app['IS_SUCCESSFUL']
X = converted_app.drop('IS_SUCCESSFUL', axis=1)

In [139]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=2022, stratify=y)

In [140]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [141]:
X_train_scaled.shape[1]

52

## Use Keras-Tuner to find best parameters to optimize the model

In [18]:
# Create a method that creates a new Sequential model with hyperparameter options:  method based off of class activities
def create_model(hp):
    nn_model = tf.keras.models.Sequential()

    # Allow keras-tuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu','tanh','selu'])
    
    # Allow keras-tuner to decide number of neurons in first layer
    # Input dimensions set to X_train_scaled.shape[1] to be automatically set to the number of features(columns)
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=80,
        step=5), activation=activation, input_dim=X_train_scaled.shape[1]))

    # Allow keras-tuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 5)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=80,
            step=5),
            activation=activation))
    
    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])
    
    return nn_model

In [19]:
# Import the keras-tuner library
import keras_tuner as kt

tuner = kt.Hyperband(
    create_model,
    overwrite=True,
    objective="val_accuracy",
    max_epochs=100,
    hyperband_iterations=10)

In [20]:
# Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=50,validation_data=(X_test_scaled,y_test))

Trial 2540 Complete [00h 01m 39s]
val_accuracy: 0.7356268167495728

Best val_accuracy So Far: 0.7379592061042786
Total elapsed time: 07h 43m 03s
INFO:tensorflow:Oracle triggered exit

In [21]:
# Get the top 2 models. from https://keras.io/guides/keras_tuner/getting_started/
models = tuner.get_best_models(num_models=2)
best_model = models[0]
# Build the model.
# Needed for `Sequential` without specified `input_shape`.
best_model.build(input_shape=(None, 28, 28))
best_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 71)                2911

 dense_1 (Dense)             (None, 66)                4752

 dense_2 (Dense)             (None, 76)                5092

 dense_3 (Dense)             (None, 71)                5467

 dense_4 (Dense)             (None, 31)                2232

 dense_5 (Dense)             (None, 26)                832

 dense_6 (Dense)             (None, 1)                 27

=================================================================
Total params: 21,313
Trainable params: 21,313
Non-trainable params: 0
_________________________________________________________________

In [22]:
tuner.results_summary()

Results summary
Results in .\untitled_project
Showing 10 best trials
<keras_tuner.engine.objective.Objective object at 0x0000029C395F1130>
Trial summary
Hyperparameters:
activation: selu
first_units: 71
num_layers: 5
units_0: 66
units_1: 76
units_2: 71
units_3: 31
units_4: 26
tuner/epochs: 34
tuner/initial_epoch: 0
tuner/bracket: 1
tuner/round: 0
Score: 0.7379592061042786
Trial summary
Hyperparameters:
activation: relu
first_units: 31
num_layers: 4
units_0: 46
units_1: 46
units_2: 71
units_3: 76
units_4: 76
tuner/epochs: 34
tuner/initial_epoch: 12
tuner/bracket: 2
tuner/round: 1
tuner/trial_id: 0718
Score: 0.7378425598144531
Trial summary
Hyperparameters:
activation: selu
first_units: 56
num_layers: 3
units_0: 61
units_1: 46
units_2: 6
units_3: 16
units_4: 6
tuner/epochs: 100
tuner/initial_epoch: 0
tuner/bracket: 0
tuner/round: 0
Score: 0.7377259731292725
Trial summary
Hyperparameters:
activation: selu
first_units: 46
num_layers: 4
units_0: 61
units_1: 61
units_2: 31
units_3: 61
units_4: 51
tuner/epochs: 100
tuner/initial_epoch: 0
tuner/bracket: 0
tuner/round: 0
Score: 0.7377259731292725
Trial summary
Hyperparameters:
activation: relu
first_units: 26
num_layers: 4
units_0: 66
units_1: 36
units_2: 21
units_3: 11
units_4: 76
tuner/epochs: 100
tuner/initial_epoch: 34
tuner/bracket: 3
tuner/round: 3
tuner/trial_id: 1219
Score: 0.7377259731292725
Trial summary
Hyperparameters:
activation: relu
first_units: 71
num_layers: 5
units_0: 56
units_1: 71
units_2: 21
units_3: 21
units_4: 66
tuner/epochs: 100
tuner/initial_epoch: 0
tuner/bracket: 0
tuner/round: 0
Score: 0.737609326839447
Trial summary
Hyperparameters:
activation: relu
first_units: 36
num_layers: 4
units_0: 46
units_1: 66
units_2: 76
units_3: 6
units_4: 66
tuner/epochs: 100
tuner/initial_epoch: 34
tuner/bracket: 1
tuner/round: 1
tuner/trial_id: 1260
Score: 0.737609326839447
Trial summary
Hyperparameters:
activation: relu
first_units: 26
num_layers: 2
units_0: 71
units_1: 26
units_2: 1
units_3: 6
units_4: 76
tuner/epochs: 100
tuner/initial_epoch: 0
tuner/bracket: 0
tuner/round: 0
Score: 0.737609326839447
Trial summary
Hyperparameters:
activation: relu
first_units: 76
num_layers: 3
units_0: 51
units_1: 41
units_2: 46
units_3: 51
units_4: 31
tuner/epochs: 34
tuner/initial_epoch: 0
tuner/bracket: 1
tuner/round: 0
Score: 0.7374927401542664
Trial summary
Hyperparameters:
activation: relu
first_units: 46
num_layers: 4
units_0: 36
units_1: 56
units_2: 41
units_3: 11
units_4: 31
tuner/epochs: 100
tuner/initial_epoch: 0
tuner/bracket: 0
tuner/round: 0
Score: 0.7374927401542664

## Compile, Train and Evaluate the Model

In [150]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_inputs = X_train.shape[1]
hidden_layer1 = 66
hidden_layer2 = 36
hidden_layer3 = 21
hidden_layer4 = 11
hidden_layer5 = 76

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer1, input_dim=number_inputs, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer3, activation="relu"))

# Fourth hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer4, activation="relu"))

# Fifth hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer5, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_19"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_110 (Dense)           (None, 66)                3498

 dense_111 (Dense)           (None, 36)                2412

 dense_112 (Dense)           (None, 21)                777

 dense_113 (Dense)           (None, 11)                242

 dense_114 (Dense)           (None, 76)                912

 dense_115 (Dense)           (None, 1)                 77

=================================================================
Total params: 7,918
Trainable params: 7,918
Non-trainable params: 0
_________________________________________________________________

In [151]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adamax", metrics=["accuracy"])

In [152]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 1s 851us/step - loss: 0.5927 - accuracy: 0.7105
Epoch 2/100
804/804 [==============================] - 1s 835us/step - loss: 0.5569 - accuracy: 0.7274
Epoch 3/100
804/804 [==============================] - 1s 852us/step - loss: 0.5515 - accuracy: 0.7298
Epoch 4/100
804/804 [==============================] - 1s 832us/step - loss: 0.5496 - accuracy: 0.7303
Epoch 5/100
804/804 [==============================] - 1s 833us/step - loss: 0.5479 - accuracy: 0.7314
Epoch 6/100
804/804 [==============================] - 1s 835us/step - loss: 0.5461 - accuracy: 0.7314
Epoch 7/100
804/804 [==============================] - 1s 832us/step - loss: 0.5459 - accuracy: 0.7314
Epoch 8/100
804/804 [==============================] - 1s 837us/step - loss: 0.5444 - accuracy: 0.7323
Epoch 9/100
804/804 [==============================] - 1s 847us/step - loss: 0.5439 - accuracy: 0.7328
Epoch 10/100
804/804 [==============================] - 1s 837us/step - loss: 0.5434 - accuracy: 0.7328
Epoch 11/100
804/804 [==============================] - 1s 846us/step - loss: 0.5428 - accuracy: 0.7333
Epoch 12/100
804/804 [==============================] - 1s 841us/step - loss: 0.5425 - accuracy: 0.7305
Epoch 13/100
804/804 [==============================] - 1s 861us/step - loss: 0.5415 - accuracy: 0.7331
Epoch 14/100
804/804 [==============================] - 1s 835us/step - loss: 0.5416 - accuracy: 0.7321
Epoch 15/100
804/804 [==============================] - 1s 846us/step - loss: 0.5410 - accuracy: 0.7331
Epoch 16/100
804/804 [==============================] - 1s 833us/step - loss: 0.5411 - accuracy: 0.7335
Epoch 17/100
804/804 [==============================] - 1s 836us/step - loss: 0.5408 - accuracy: 0.7337
Epoch 18/100
804/804 [==============================] - 1s 835us/step - loss: 0.5401 - accuracy: 0.7333
Epoch 19/100
804/804 [==============================] - 1s 830us/step - loss: 0.5404 - accuracy: 0.7346
Epoch 20/100
804/804 [==============================] - 1s 840us/step - loss: 0.5396 - accuracy: 0.7337
Epoch 21/100
804/804 [==============================] - 1s 847us/step - loss: 0.5399 - accuracy: 0.7333
Epoch 22/100
804/804 [==============================] - 1s 833us/step - loss: 0.5396 - accuracy: 0.7343
Epoch 23/100
804/804 [==============================] - 1s 837us/step - loss: 0.5392 - accuracy: 0.7352
Epoch 24/100
804/804 [==============================] - 1s 840us/step - loss: 0.5387 - accuracy: 0.7350
Epoch 25/100
804/804 [==============================] - 1s 837us/step - loss: 0.5388 - accuracy: 0.7351
Epoch 26/100
804/804 [==============================] - 1s 842us/step - loss: 0.5386 - accuracy: 0.7349
Epoch 27/100
804/804 [==============================] - 1s 841us/step - loss: 0.5384 - accuracy: 0.7356
Epoch 28/100
804/804 [==============================] - 1s 832us/step - loss: 0.5380 - accuracy: 0.7359
Epoch 29/100
804/804 [==============================] - 1s 847us/step - loss: 0.5378 - accuracy: 0.7330
Epoch 30/100
804/804 [==============================] - 1s 838us/step - loss: 0.5378 - accuracy: 0.7362
Epoch 31/100
804/804 [==============================] - 1s 847us/step - loss: 0.5378 - accuracy: 0.7349
Epoch 32/100
804/804 [==============================] - 1s 845us/step - loss: 0.5375 - accuracy: 0.7362
Epoch 33/100
804/804 [==============================] - 1s 833us/step - loss: 0.5375 - accuracy: 0.7348
Epoch 34/100
804/804 [==============================] - 1s 835us/step - loss: 0.5369 - accuracy: 0.7358
Epoch 35/100
804/804 [==============================] - 1s 836us/step - loss: 0.5371 - accuracy: 0.7361
Epoch 36/100
804/804 [==============================] - 1s 835us/step - loss: 0.5367 - accuracy: 0.7372
Epoch 37/100
804/804 [==============================] - 1s 832us/step - loss: 0.5370 - accuracy: 0.7357
Epoch 38/100
804/804 [==============================] - 1s 854us/step - loss: 0.5364 - accuracy: 0.7352
Epoch 39/100
804/804 [==============================] - 1s 840us/step - loss: 0.5363 - accuracy: 0.7369
Epoch 40/100
804/804 [==============================] - 1s 846us/step - loss: 0.5358 - accuracy: 0.7364
Epoch 41/100
804/804 [==============================] - 1s 838us/step - loss: 0.5361 - accuracy: 0.7362
Epoch 42/100
804/804 [==============================] - 1s 832us/step - loss: 0.5355 - accuracy: 0.7365
Epoch 43/100
804/804 [==============================] - 1s 833us/step - loss: 0.5357 - accuracy: 0.7380
Epoch 44/100
804/804 [==============================] - 1s 840us/step - loss: 0.5354 - accuracy: 0.7374
Epoch 45/100
804/804 [==============================] - 1s 842us/step - loss: 0.5351 - accuracy: 0.7360
Epoch 46/100
804/804 [==============================] - 1s 832us/step - loss: 0.5351 - accuracy: 0.7377
Epoch 47/100
804/804 [==============================] - 1s 842us/step - loss: 0.5352 - accuracy: 0.7370
Epoch 48/100
804/804 [==============================] - 1s 836us/step - loss: 0.5349 - accuracy: 0.7379
Epoch 49/100
804/804 [==============================] - 1s 835us/step - loss: 0.5346 - accuracy: 0.7374
Epoch 50/100
804/804 [==============================] - 1s 851us/step - loss: 0.5348 - accuracy: 0.7378
Epoch 51/100
804/804 [==============================] - 1s 837us/step - loss: 0.5346 - accuracy: 0.7370
Epoch 52/100
804/804 [==============================] - 1s 863us/step - loss: 0.5341 - accuracy: 0.7380
Epoch 53/100
804/804 [==============================] - 1s 847us/step - loss: 0.5343 - accuracy: 0.7385
Epoch 54/100
804/804 [==============================] - 1s 832us/step - loss: 0.5342 - accuracy: 0.7391
Epoch 55/100
804/804 [==============================] - 1s 845us/step - loss: 0.5341 - accuracy: 0.7371
Epoch 56/100
804/804 [==============================] - 1s 867us/step - loss: 0.5343 - accuracy: 0.7377
Epoch 57/100
804/804 [==============================] - 1s 838us/step - loss: 0.5334 - accuracy: 0.7388
Epoch 58/100
804/804 [==============================] - 1s 840us/step - loss: 0.5343 - accuracy: 0.7385
Epoch 59/100
804/804 [==============================] - 1s 850us/step - loss: 0.5336 - accuracy: 0.7381
Epoch 60/100
804/804 [==============================] - 1s 840us/step - loss: 0.5333 - accuracy: 0.7378
Epoch 61/100
804/804 [==============================] - 1s 861us/step - loss: 0.5332 - accuracy: 0.7384
Epoch 62/100
804/804 [==============================] - 1s 846us/step - loss: 0.5335 - accuracy: 0.7372
Epoch 63/100
804/804 [==============================] - 1s 841us/step - loss: 0.5329 - accuracy: 0.7381
Epoch 64/100
804/804 [==============================] - 1s 836us/step - loss: 0.5334 - accuracy: 0.7383
Epoch 65/100
804/804 [==============================] - 1s 838us/step - loss: 0.5331 - accuracy: 0.7381
Epoch 66/100
804/804 [==============================] - 1s 832us/step - loss: 0.5332 - accuracy: 0.7374
Epoch 67/100
804/804 [==============================] - 1s 836us/step - loss: 0.5330 - accuracy: 0.7383
Epoch 68/100
804/804 [==============================] - 1s 852us/step - loss: 0.5327 - accuracy: 0.7383
Epoch 69/100
804/804 [==============================] - 1s 845us/step - loss: 0.5327 - accuracy: 0.7381
Epoch 70/100
804/804 [==============================] - 1s 836us/step - loss: 0.5329 - accuracy: 0.7388
Epoch 71/100
804/804 [==============================] - 1s 838us/step - loss: 0.5331 - accuracy: 0.7384
Epoch 72/100
804/804 [==============================] - 1s 837us/step - loss: 0.5323 - accuracy: 0.7377
Epoch 73/100
804/804 [==============================] - 1s 838us/step - loss: 0.5326 - accuracy: 0.7382
Epoch 74/100
804/804 [==============================] - 1s 851us/step - loss: 0.5324 - accuracy: 0.7387
Epoch 75/100
804/804 [==============================] - 1s 843us/step - loss: 0.5324 - accuracy: 0.7390
Epoch 76/100
804/804 [==============================] - 1s 842us/step - loss: 0.5325 - accuracy: 0.7389
Epoch 77/100
804/804 [==============================] - 1s 846us/step - loss: 0.5324 - accuracy: 0.7372
Epoch 78/100
804/804 [==============================] - 1s 835us/step - loss: 0.5321 - accuracy: 0.7386
Epoch 79/100

804/804 [==============================] - 1s 840us/step - loss: 0.5317 - accuracy: 0.7386
Epoch 80/100
804/804 [==============================] - 1s 846us/step - loss: 0.5319 - accuracy: 0.7398
Epoch 81/100
804/804 [==============================] - 1s 837us/step - loss: 0.5320 - accuracy: 0.7395
Epoch 82/100
804/804 [==============================] - 1s 838us/step - loss: 0.5310 - accuracy: 0.7382
Epoch 83/100
804/804 [==============================] - 1s 850us/step - loss: 0.5317 - accuracy: 0.7392
Epoch 84/100
804/804 [==============================] - 1s 845us/step - loss: 0.5318 - accuracy: 0.7385
Epoch 85/100
804/804 [==============================] - 1s 840us/step - loss: 0.5320 - accuracy: 0.7389
Epoch 86/100
804/804 [==============================] - 1s 850us/step - loss: 0.5315 - accuracy: 0.7393
Epoch 87/100
804/804 [==============================] - 1s 838us/step - loss: 0.5314 - accuracy: 0.7383
Epoch 88/100
804/804 [==============================] - 1s 841us/step - loss: 0.5317 - accuracy: 0.7394
Epoch 89/100
804/804 [==============================] - 1s 841us/step - loss: 0.5313 - accuracy: 0.7402
Epoch 90/100
804/804 [==============================] - 1s 841us/step - loss: 0.5310 - accuracy: 0.7392
Epoch 91/100
804/804 [==============================] - 1s 838us/step - loss: 0.5312 - accuracy: 0.7392
Epoch 92/100
804/804 [==============================] - 1s 847us/step - loss: 0.5308 - accuracy: 0.7393
Epoch 93/100
804/804 [==============================] - 1s 840us/step - loss: 0.5307 - accuracy: 0.7395
Epoch 94/100
804/804 [==============================] - 1s 848us/step - loss: 0.5312 - accuracy: 0.7385
Epoch 95/100
804/804 [==============================] - 1s 842us/step - loss: 0.5313 - accuracy: 0.7401
Epoch 96/100
804/804 [==============================] - 1s 841us/step - loss: 0.5309 - accuracy: 0.7393
Epoch 97/100
804/804 [==============================] - 1s 847us/step - loss: 0.5308 - accuracy: 0.7400
Epoch 98/100
804/804 [==============================] - 1s 851us/step - loss: 0.5307 - accuracy: 0.7395
Epoch 99/100
804/804 [==============================] - 1s 840us/step - loss: 0.5307 - accuracy: 0.7391
Epoch 100/100
804/804 [==============================] - 1s 846us/step - loss: 0.5305 - accuracy: 0.7393

In [153]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5558 - accuracy: 0.7367 - 279ms/epoch - 1ms/step
Loss: 0.5558176040649414, Accuracy: 0.7366763949394226

It seems no matter the parameters I change I cannot even get to 74%.  I have tried several binning schemes and tried varying the optimizer as well as using keras tuner to try so many layer values, activations and epochs.  I didn't want to rerun the tuner again due to time constraints.  I tried dropping status column and it got worse, then I dropped income amount and it didn't really change.  I then put them back.  Last I tried changing the optimizer as well and it seemed adamax did slightly better.

In [ ]:
# Export our model to HDF5 file
model.save('path/to/location')